### ISSUE TITLE
Correct architecture 

### ISSUE THREAD

**Issue by Sha88y** [vives-project-xp/GreenhouseWaterSystem#29]
Correct the name of the float switches on the architecture file

**Comment by Sha88y** [comment]
added all  the connections and correct names of the pins.
just need the right pin connection on the esp and then everything is done

**Comment by BramDe** [comment]
![Architectuur (1) drawio](https://github.com/user-attachments/assets/5c851ace-461e-41f1-ad40-db7ee8d287c7)
added the ground line for the voltter switches
